function [scenario, egoVehicle] = changeLangeLeftWaypoints()
% createDrivingScenario Returns the drivingScenario defined in the Designer

% Generated by MATLAB(R) 9.14 (R2023a) and Automated Driving Toolbox 3.7 (R2023a).
% Generated on: 09-Aug-2023 13:02:59

% Construct a drivingScenario object.
scenario = drivingScenario;

% Add all road segments
roadCenters = [59.4 -0.2 0;
    -9.2 0.1 0];
laneSpecification = lanespec(2);
road(scenario, roadCenters, 'Lanes', laneSpecification, 'Name', 'Road');

% Add the ego vehicle
egoVehicle = vehicle(scenario, ...
    'ClassID', 1, ...
    'Position', [-5.93127627606 -2.20895520317019 0], ...
    'Mesh', driving.scenario.carMesh, ...
    'Name', 'Car');
waypoints = [-5.93127627606 -2.20895520317019 0;
    5.3 -1.6 0;
    14.8 0.9 0;
    24.7 1.4 0;
    33.7 1.4 0];
speed = [50;50;50;50;50];
waittime = [0;0;0;0;0];
trajectory(egoVehicle, waypoints, speed, waittime);

